version: '3.8'

services:
  document-scanner:
    image: nginx:alpine
    container_name: document-scanner
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge